inputs:
  github_token:
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        python3 -m venv venv
        . venv/bin/activate
        python -m pip install briefcase
        briefcase create
        briefcaes update -r
        briefcase build
        briefcase package

    - name: Create or update GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.github_token }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifacts: "dist/*"
        allowUpdates: true
        replacesArtifacts: false
        draft: false
        prerelease: false
