name: Default release workflow
on: 
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: read

jobs:
  release-ubuntu_24_04:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        shell: bash
        run: |
          sudo apt install -y libcairo2-dev libgirepository1.0-dev
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install briefcase
          briefcase create
          briefcase update -r
          briefcase build
          briefcase package
      - name: Create or update GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.event.release.tag_name }}
          artifacts: "dist/*"
          allowUpdates: true
          replacesArtifacts: false
          draft: false
          prerelease: false

  release-windows:
    runs-on: windows-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        shell: bash
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install briefcase
          briefcase create
          briefcase update -r
          briefcase build
          briefcase package
      - name: Create or update GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.event.release.tag_name }}
          artifacts: "dist/*"
          allowUpdates: true
          replacesArtifacts: false
          draft: false
          prerelease: false
